config/routes.rb
Turnchannelfm::Application.routes.draw do
  ActiveAdmin.routes(self)

  mount Resque::Server.new, :at => "/resque"

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :tracks do
    member do
      post :toggle_save
    end
  end

  match '/discover' => 'tracks#discover'
  match '/discover/:tag' => 'tracks#discover'
  match '/tracks/search/:q' => 'tracks#search'
  match '/tracks/search' => 'tracks#search'

  match '/saved' => 'tracks#saved'
  match '/playing_history' => 'tracks#playing_history'

  match '/a' => "tracks#index"

  match '/channel.html' => 'tracks#channel'

  root :to => "tracks#index"

end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :title, :full_title, :plays, :cached_plays, :sc_url, :sc_id, :artwork_url, :purchase_url, :description, :duration, :label_name, :artist, :genre_id, :created_at, :user_id, :tag_id, :searchable_metadata

  has_permalink :full_title

  belongs_to :tag
  belongs_to :user

  has_many :favorites
  has_many :users_fav, :through => :favorites, :source => :user

  validates :sc_url, :presence => true, :uniqueness => true

  before_save :parse_title

  def self.build(user_id, tag, track_hash)
    if track_hash
      unless (track = Track.find_by_sc_url(track_hash.permalink_url))
        if track_hash.stream_url && track_hash.artwork_url
          track = Track.create(
            :full_title => track_hash.title,
            :sc_url => track_hash.permalink_url,
            :sc_id => track_hash.id,
            :artwork_url => track_hash.artwork_url,
            :purchase_url => track_hash.purchase_url,
            :description => track_hash.description,
            :duration => track_hash.duration,
            :plays => 0,
            :cached_plays => 0,
            :user_id => user_id,
            :tag_id => tag.id
          )
        end
      end
    end
    track
  end

  def play
    self.plays = self.plays + 1
    self.cached_plays = self.cached_plays + 1
    self.save
  end

  def parse_title
    title, *rest = self.full_title.split(/ by /)

    self.title = title
    _rest = rest.join(' by ')
    self.artist = _rest.split(/ - /).first
    self.full_title = self.full_title.downcase
  end

  def f_full_title
    "#{self.f_title} by #{self.f_artist}"
  end

  def f_title
    if self.title
      self.title.split(" ").map{|t| t.capitalize}.join(' ')
    else
      ""
    end
  end

  def f_artist
    if self.artist
      self.artist.split(" ").map{|t| t.capitalize}.join(' ')
    else
      ""
    end
  end

  def toggle_save(user)
    if (track_save = Favorite.find_by_user_id_and_track_id(user.id, self.id))
      track_save.destroy
      0
    else
      Favorite.create(:user_id => user.id, :track_id => self.id)
      1
    end
  end

  def find_youtube_video!
    title = self.full_title

    client = YouTubeIt::Client.new

    if (res = client.videos_by(:query => title))
      if (videos = res.videos)
        if (video = videos.first)
          if (self.duration/1000 - video.duration).abs < 10
            return "http://www.youtube.com/watch?v=#{video.unique_id}"
          end
        end
      end
    end

    nil
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_filter :authenticate_user!, :only => [:toggle_save]
  before_filter :manage_session, :except => [:show, :channel, :toggle_save]

  def index
    @tags = Tag.all

    @popular_tracks = Track.order("cached_plays DESC").limit(10)
    @new_tracks = Track.order("created_at DESC").limit(70)
    #@featured_tracks = Track.order("created_at DESC").limit(8)
    @featured_tracks = [Track.find_by_id(3041), Track.find_by_id(2991), Track.find_by_id(2821), Track.find_by_id(2759), Track.find_by_id(2842), Track.find_by_id(2992), Track.find_by_id(3050), Track.find_by_id(2970)]
    session[:auto_play] = true
  end

  def discover
    @tag_name = params[:tag]

    tag = Tag.find_by_name(@tag_name)
    if tag
      @track = tag.tracks.order("RANDOM()").limit(1).first
    else
      @track = Track.order("RANDOM()").limit(1).first
    end

    session[:type] = nil
    redirect_to track_url(@track.permalink)
  end

  def saved
    unless current_user.blank?
      @play_queue = current_user.fav_tracks.reverse

      if @play_queue.size > 0
        session[:type] = 'saved tracks'
        session[:play_queue] = @play_queue.map{|z|z.id}
        redirect_to track_url(@play_queue.first.permalink)
      else
        redirect_to '/discover/dubstep'
      end
    else
      redirect_to root_url
    end
  end

  def search
    session[:auto_play] = true

    unless params[:q].blank?
      @q = params[:q]

      @tracks = Track.find(:all, :conditions => ['full_title LIKE ?', "%#{@q.downcase}%"], :limit => 21)
    else
      begin
        redirect_to :back
      rescue ActionController::RedirectBackError
        redirect_to root_path
      end
    end
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
    @track = Track.find_by_permalink(params[:id])
    @tags = Tag.all

    if @track
      @track.play
      @next_track = Track.where(:tag_id => @track.tag.id).where("id < ?", @track.id).order("id DESC").limit(1).first

      render :layout => false;
    else
      redirect_to root_path
    end
  end

  def toggle_save
    @track = Track.find_by_id(params[:id])
    state = @track.toggle_save(current_user)

    render :json => {:state => state}
  end

  def channel
    cache_expire = 1.year
    response.headers["Pragma"] = "public"
    response.headers["Cache-Control"] = "max-age=#{cache_expire.to_i}"
    response.headers["Expires"] = (Time.now + cache_expire).strftime("%d %m %Y %H:%I:%S %Z")
    render :layout => false, :inline => "<script src='//connect.facebook.net/en_US/all.js#xfbml=1&appId=242371292554988'></script>"
  end

  def manage_session
    session[:auto_play] = true
  end

  # GET /tracks/new
  # GET /tracks/new.json
  ##def new
  #  @track = Track.new

  #  respond_to do |format|
  #    format.html # new.html.erb
  #    format.json { render json: @track }
  #  end
  #end

  # GET /tracks/1/edit
  ##def edit
  #  @track = Track.find(params[:id])
  #end

  # POST /tracks
  # POST /tracks.json
  #def create
  #  @track = Track.new(params[:track])

  #  respond_to do |format|
  #    if @track.save
  #      format.html { redirect_to @track, notice: 'Track was successfully created.' }
  #      format.json { render json: @track, status: :created, location: @track }
  #    else
  #      format.html { render action: "new" }
  #      format.json { render json: @track.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # PUT /tracks/1
  # PUT /tracks/1.json
  #def update
  #  @track = Track.find(params[:id])

  #  respond_to do |format|
  #    if @track.update_attributes(params[:track])
  #      format.html { redirect_to @track, notice: 'Track was successfully updated.' }
  #      format.json { head :no_content }
  #    else
  #      format.html { render action: "edit" }
  #      format.json { render json: @track.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  #def destroy
  #  @track = Track.find(params[:id])
  #  @track.destroy

  #  respond_to do |format|
  #    format.html { redirect_to tracks_url }
  #    format.json { head :no_content }
  #  end
  #end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.haml
= form_for @track do |f|
  - if @track.errors.any?
    #error_explanation
      %h2= "#{pluralize(@track.errors.count, "error")} prohibited this track from being saved:"
      %ul
        - @track.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/tracks/_playlists.html.haml
- @track.playlists.each do |playlist|
  .playlist
    .playlist-avatar
      %a{:href => playlist_url(playlist.id)}
        - playlist.tracks[0..8].each do |track|
          = image_tag track.artwork_url.gsub('large','badge')
    .playlist-title
      = playlist.title

app/views/tracks/_track_entry.html.haml
%article.track{:style => style}
  %a{:href => track_url(track.permalink)}
    = image_tag track.artwork_url.gsub('large','t300x300')
    .track-play
      %i.icon-play.icon-white
    .track-stats
      .track-plays
        ►
        = track.cached_plays
      .track-tags
        %span.label.label-inverse= track.tag.name
    .track-info
      .track-artist
        = track.artist
      .track-title
        = track.title

app/views/tracks/edit.html.haml
%h1 Editing track

= render 'form'

= link_to 'Show', @track
\|
= link_to 'Back', tracks_path

app/views/tracks/index.html.haml
.guide-bar
  .guide
    - if current_user.blank?
      .guide-container
        %h5 Discover the best EDM
        %a.register-btn.btn.btn-primary{:href => user_omniauth_authorize_path(:facebook), :target => '_blank'} Register
    - else
      .guide-container
        .profile
          = image_tag current_user.avatar
          .name
            = current_user.name
      .guide-container#favorites-guide
        %h5 Favorites
        %ul
          %a{:href => "/saved"}
            - selected = ''
            - selected = 'selected' unless session[:type].blank?
            %li{:class => selected}
              %i.icon-star
              Saved Tracks
    .guide-container#discover-guide
      %h5 Play me some...
      %ul
        - @tags.each do |tag|
          %a{:href => "/discover/#{tag.name}"}
            %li
              %i.icon-headphones
              = tag.name.camelize
  .share-turnchannel
    %h5 Help spread the word
    .social-connect
      .social#social-tw
        %a{:href=>"https://twitter.com/TurnChannel", :class=>"twitter-follow-button", :'data-show-count'=>"false", :'data-dnt'=>"true"} Follow @TurnChannel
      .social#social-fb
        .fb-like{:'data-href'=>"http://www.facebook.com/TurnChannel", :'data-send'=>"false", :'data-layout'=>"button_count", :'data-width'=>"450", :'data-show-faces'=>"false"}

.home-feed
  .new-tracks-container
    .new-tracks-heading
      %h4 New on TurnChannel
    .new-track-items
      - date = nil
      - @new_tracks.each do |track|
        - if date != track.created_at.to_date
          - date = track.created_at.to_date
          %h4= date.to_time.strftime("%A, %b %-d, %Y")
        %article.new-track-item.track
          %a{:href => track_url(track.permalink), :target => '_blank'}
            = image_tag track.artwork_url
            .new-track-description
              .track-item-title= track.f_title
              .track-item-artist= track.f_artist
            .track-play
              %i.icon-play.icon-white
            .genre
              %span.label.label-inverse= track.tag.name

app/views/tracks/new.html.haml
%h1 New track

= render 'form'

= link_to 'Back', tracks_path

app/views/tracks/search.html.haml
.search-tracks-container
  .search-tracks-heading
    %h4
      Search results for "
      = @q
      "
  .search-track-items
    - if @tracks.empty?
      Could not find any tracks. Try again.
    - else
      - @tracks.each do |track|
        %article.search-track-item.track
          %a{:href => track_url(track.permalink)}
            = image_tag track.artwork_url
            .search-track-description
              .track-item-title= track.f_title
              .track-item-artist= track.f_artist
            .track-play
              %i.icon-play.icon-white
            .genre
              %span.label.label-inverse= track.tag.name

app/views/tracks/show.html.haml
!!!
%html{:lang => 'en'}
  %head
    = render :partial => 'layouts/head'
  %body.share-page
    .card
      .track-containerr{:'track-id' => @track.sc_id}
        = image_tag @track.artwork_url.gsub('large','t500x500')
        .progress-bar
          .seek
      .info
        .artist
          = image_tag @track.user.avatar, :class => 'avatar'
          %h2= @track.user.name
        %h1
          .inner
            %p= @track.full_title
        %a.next-track{:href => track_url(@next_track.permalink)}
          = image_tag @next_track.artwork_url
          %h2
            .inner
              %p= @next_track.full_title