config/routes.rb
Turnchannelfm::Application.routes.draw do
  ActiveAdmin.routes(self)

  mount Resque::Server.new, :at => "/resque"

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :tracks do
    member do
      post :toggle_save
    end
  end

  match '/discover' => 'tracks#discover'
  match '/discover/:tag' => 'tracks#discover'
  match '/tracks/search/:q' => 'tracks#search'
  match '/tracks/search' => 'tracks#search'

  match '/saved' => 'tracks#saved'
  match '/playing_history' => 'tracks#playing_history'

  match '/a' => "tracks#index"

  match '/channel.html' => 'tracks#channel'

  root :to => "tracks#index"

end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_artists.html.haml
%table
  %thead
    %th
    %th
    %th{:width => '50%'} Title
    %th
    %th{:width => '50%'} Artist
    %th Duration
    %th Plays
  %tbody
    - @playlist.tracks.each_with_index do |track, i|

      - minutes = (track.duration / (60*1000)).floor
      - seconds = ((track.duration - minutes*60*1000) / 1000).floor
      - if seconds < 10
        - duration = "#{minutes}:0#{seconds}"
      - else
        - duration = "#{minutes}:#{seconds}"

      - c = 'track'
      - if i % 2 == 1
        - c = 'track odd'
      %tr{:'track-id' => track.id, :class => c}
        %td.play-column
          %i.icon-play{:title => 'Play'}
        %td.star-column
          %i.icon-star-empty{:title => 'Favorite'}
        %td.title-column= link_to track.title, '#'
        %td.buy-column
          - unless track.purchase_url.blank?
            %a{:href => track.purchase_url, :title => 'Purchase', :target => '_blank'}
              %i.icon-shopping-cart
        %td.artist-column= link_to track.artist, '#'
        %td.duration-column= duration
        %td.plays-column= track.plays

app/views/playlists/_comments.html.haml
%table
  %thead
    %th
    %th
    %th{:width => '50%'} Title
    %th
    %th{:width => '50%'} Artist
    %th Duration
    %th Plays
  %tbody
    - @playlist.tracks.each_with_index do |track, i|

      - minutes = (track.duration / (60*1000)).floor
      - seconds = ((track.duration - minutes*60*1000) / 1000).floor
      - if seconds < 10
        - duration = "#{minutes}:0#{seconds}"
      - else
        - duration = "#{minutes}:#{seconds}"

      - c = 'track'
      - if i % 2 == 1
        - c = 'track odd'
      %tr{:'track-id' => track.id, :class => c}
        %td.play-column
          %i.icon-play{:title => 'Play'}
        %td.star-column
          %i.icon-star-empty{:title => 'Favorite'}
        %td.title-column= link_to track.title, '#'
        %td.buy-column
          - unless track.purchase_url.blank?
            %a{:href => track.purchase_url, :title => 'Purchase', :target => '_blank'}
              %i.icon-shopping-cart
        %td.artist-column= link_to track.artist, '#'
        %td.duration-column= duration
        %td.plays-column= track.plays

app/views/playlists/_form.html.haml
= form_for @playlist do |f|
  - if @playlist.errors.any?
    #error_explanation
      %h2= "#{pluralize(@playlist.errors.count, "error")} prohibited this playlist from being saved:"
      %ul
        - @playlist.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/playlists/_similar_playlists.html.haml
.playlists-container
  - @similar_playlists.each do |playlist|
    .playlist
      .playlist-avatar
        %a{:href => playlist_url(playlist.id)}
          - playlist.tracks[0..8].each do |track|
            = image_tag track.artwork_url.gsub('large','badge')
      .playlist-title
        = playlist.title

app/views/playlists/_tracks.html.haml
%table
  %tbody
    - @playlist.tracks.each_with_index do |track, i|

      - minutes = (track.duration / (60*1000)).floor
      - seconds = ((track.duration - minutes*60*1000) / 1000).floor
      - if seconds < 10
        - duration = "#{minutes}:0#{seconds}"
      - else
        - duration = "#{minutes}:#{seconds}"

      - c = 'track'
      - if i % 2 == 1
        - c = 'track odd'
      %tr{:'track-id' => track.id, :class => c}
        %td.play-column
          %i.icon-play{:title => 'Play'}
        %td.star-column
          %i.icon-star-empty{:title => 'Favorite'}
        %td.title-column= link_to track.title, track_url(track.id)
        %td.buy-column
          - unless track.purchase_url.blank?
            %a{:href => track.purchase_url, :title => 'Purchase', :target => '_blank'}
              %i.icon-shopping-cart
        %td.artist-column= link_to track.artist, '#'
        %td.duration-column= duration
        %td.plays-column= track.plays

app/views/playlists/discover.html.haml
.discover
  %h1 Discover Tracks
  .new-playlists
    %h3 New tracks
    - @playlists.each do |playlist|
      .playlist
        .playlist-avatar
          %a{:href => playlist_url(playlist.id)}
            - playlist.tracks[0..8].each do |track|
              = image_tag track.artwork_url.gsub('large','badge')
        .playlist-title
          = playlist.title
  .new-playlists
    %h3 Popular tracks
    - @playlists.each do |playlist|
      .playlist
        .playlist-avatar
          - playlist.tracks[0..8].each do |track|
            = image_tag track.artwork_url.gsub('large','badge')
        .playlist-title
          = playlist.title

app/views/playlists/edit.html.haml
%h1 Editing playlist

= render 'form'

= link_to 'Show', @playlist
\|
= link_to 'Back', playlists_path

app/views/playlists/index.html.haml
.playlists-container
  - @playlists.first.tracks.each_with_index do |track, i|
    - style = ''
    - if i % 3 == 2
      - style = 'margin-right: 0;'
    .playlist{:style => style}
      %a{:href => track_url(track.id)}
        = image_tag track.artwork_url.gsub('large','t300x300')
        .playlist-stats
          .playlist-plays
            ►
            = track.plays
        .playlist-info
          .playlist-artist
            = track.artist
          .playlist-title
            = track.title

app/views/playlists/new.html.haml
%h1 New playlist

= render 'form'

= link_to 'Back', playlists_path

app/views/playlists/show.html.haml
.playlist-container
  .playlist-header
    .playlist-avatar
      - @playlist.tracks[0..8].each do |track|
        = image_tag track.artwork_url.gsub('large','badge')
    .playlist-title
      %h3
        = @playlist.title
        %span
          by
          = link_to @playlist.user.name
      .playlist-tags
      .playlist-playall
        %button#playall.btn
          %i.icon-headphones
          Play All
  .playlist-tracks
    .playlist-tracks-header.navbar.navbar-inner.no-border-radius
      %nav
        %ul.nav
          %li.active= link_to 'Tracks', tracks_playlist_url(@playlist.id)

    .playlist-tracks-content
      - if params[:action] == 'show' || params[:action] == 'tracks'
        = render :partial => "tracks", :playlist => @playlist
    .playlist-comments-content.hide
      - if params[:action] == 'comments'
        = render :partial => "comments", :playlist => @playlist
  .playlist-related
    .playlist-tracks-header.navbar.navbar-inner.no-border-radius
      %nav
        %ul.nav
          %li.active= link_to 'Similar Playlists', tracks_playlist_url(@playlist.id)
          %li= link_to 'Comments', comments_playlist_url(@playlist.id)
    .playlist-related-content
      = render :partial => "similar_playlists", :playlist => @similar_playlists